USE [master]
GO

/****** Object:  Database [ECommerceDb]    Script Date: 18/05/2025 13:30:56 ******/
CREATE DATABASE [ECommerceDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ECommerceDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ECommerceDb.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ECommerceDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ECommerceDb_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ECommerceDb] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ECommerceDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ECommerceDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ECommerceDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ECommerceDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ECommerceDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ECommerceDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [ECommerceDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ECommerceDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ECommerceDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ECommerceDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ECommerceDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ECommerceDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ECommerceDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ECommerceDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ECommerceDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ECommerceDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ECommerceDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ECommerceDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ECommerceDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ECommerceDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ECommerceDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ECommerceDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ECommerceDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ECommerceDb] SET RECOVERY FULL 
GO

ALTER DATABASE [ECommerceDb] SET  MULTI_USER 
GO

ALTER DATABASE [ECommerceDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ECommerceDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ECommerceDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ECommerceDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ECommerceDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ECommerceDb] SET  READ_WRITE 
GO


